#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLBT")]
	public partial class QLBTDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBenhNhan(BenhNhan instance);
    partial void UpdateBenhNhan(BenhNhan instance);
    partial void DeleteBenhNhan(BenhNhan instance);
    partial void InsertThuoc(Thuoc instance);
    partial void UpdateThuoc(Thuoc instance);
    partial void DeleteThuoc(Thuoc instance);
    partial void InsertchiTietHoaDonNhap(chiTietHoaDonNhap instance);
    partial void UpdatechiTietHoaDonNhap(chiTietHoaDonNhap instance);
    partial void DeletechiTietHoaDonNhap(chiTietHoaDonNhap instance);
    partial void InsertchiTietHoaDonXuat(chiTietHoaDonXuat instance);
    partial void UpdatechiTietHoaDonXuat(chiTietHoaDonXuat instance);
    partial void DeletechiTietHoaDonXuat(chiTietHoaDonXuat instance);
    partial void InsertDonViTinh(DonViTinh instance);
    partial void UpdateDonViTinh(DonViTinh instance);
    partial void DeleteDonViTinh(DonViTinh instance);
    partial void InsertHoaDonNhap(HoaDonNhap instance);
    partial void UpdateHoaDonNhap(HoaDonNhap instance);
    partial void DeleteHoaDonNhap(HoaDonNhap instance);
    partial void InsertHoaDonXuat(HoaDonXuat instance);
    partial void UpdateHoaDonXuat(HoaDonXuat instance);
    partial void DeleteHoaDonXuat(HoaDonXuat instance);
    partial void InsertNhaPhanPhoi(NhaPhanPhoi instance);
    partial void UpdateNhaPhanPhoi(NhaPhanPhoi instance);
    partial void DeleteNhaPhanPhoi(NhaPhanPhoi instance);
    partial void InsertNhaSanXuat(NhaSanXuat instance);
    partial void UpdateNhaSanXuat(NhaSanXuat instance);
    partial void DeleteNhaSanXuat(NhaSanXuat instance);
    partial void InsertNhomThuoc(NhomThuoc instance);
    partial void UpdateNhomThuoc(NhomThuoc instance);
    partial void DeleteNhomThuoc(NhomThuoc instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    #endregion
		
		public QLBTDataContext() : 
				base(global::DAL.Properties.Settings.Default.QLBTConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLBTDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLBTDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLBTDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLBTDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BenhNhan> BenhNhans
		{
			get
			{
				return this.GetTable<BenhNhan>();
			}
		}
		
		public System.Data.Linq.Table<Thuoc> Thuocs
		{
			get
			{
				return this.GetTable<Thuoc>();
			}
		}
		
		public System.Data.Linq.Table<chiTietHoaDonNhap> chiTietHoaDonNhaps
		{
			get
			{
				return this.GetTable<chiTietHoaDonNhap>();
			}
		}
		
		public System.Data.Linq.Table<chiTietHoaDonXuat> chiTietHoaDonXuats
		{
			get
			{
				return this.GetTable<chiTietHoaDonXuat>();
			}
		}
		
		public System.Data.Linq.Table<DonViTinh> DonViTinhs
		{
			get
			{
				return this.GetTable<DonViTinh>();
			}
		}
		
		public System.Data.Linq.Table<HoaDonNhap> HoaDonNhaps
		{
			get
			{
				return this.GetTable<HoaDonNhap>();
			}
		}
		
		public System.Data.Linq.Table<HoaDonXuat> HoaDonXuats
		{
			get
			{
				return this.GetTable<HoaDonXuat>();
			}
		}
		
		public System.Data.Linq.Table<NhaPhanPhoi> NhaPhanPhois
		{
			get
			{
				return this.GetTable<NhaPhanPhoi>();
			}
		}
		
		public System.Data.Linq.Table<NhaSanXuat> NhaSanXuats
		{
			get
			{
				return this.GetTable<NhaSanXuat>();
			}
		}
		
		public System.Data.Linq.Table<NhomThuoc> NhomThuocs
		{
			get
			{
				return this.GetTable<NhomThuoc>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_inHoaDonBN")]
		public ISingleResult<sp_inHoaDonBNResult> sp_inHoaDonBN([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string idBN)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idBN);
			return ((ISingleResult<sp_inHoaDonBNResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_inHoaDonNhap")]
		public ISingleResult<sp_inHoaDonNhapResult> sp_inHoaDonNhap([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string maHDN)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maHDN);
			return ((ISingleResult<sp_inHoaDonNhapResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BenhNhan")]
	public partial class BenhNhan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idBN;
		
		private string _hoTen;
		
		private System.Nullable<int> _tuoi;
		
		private string _diaChi;
		
		private string _dienThoai;
		
		private EntitySet<HoaDonXuat> _HoaDonXuats;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidBNChanging(string value);
    partial void OnidBNChanged();
    partial void OnhoTenChanging(string value);
    partial void OnhoTenChanged();
    partial void OntuoiChanging(System.Nullable<int> value);
    partial void OntuoiChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OndienThoaiChanging(string value);
    partial void OndienThoaiChanged();
    #endregion
		
		public BenhNhan()
		{
			this._HoaDonXuats = new EntitySet<HoaDonXuat>(new Action<HoaDonXuat>(this.attach_HoaDonXuats), new Action<HoaDonXuat>(this.detach_HoaDonXuats));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idBN", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idBN
		{
			get
			{
				return this._idBN;
			}
			set
			{
				if ((this._idBN != value))
				{
					this.OnidBNChanging(value);
					this.SendPropertyChanging();
					this._idBN = value;
					this.SendPropertyChanged("idBN");
					this.OnidBNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoTen", DbType="NVarChar(50)")]
		public string hoTen
		{
			get
			{
				return this._hoTen;
			}
			set
			{
				if ((this._hoTen != value))
				{
					this.OnhoTenChanging(value);
					this.SendPropertyChanging();
					this._hoTen = value;
					this.SendPropertyChanged("hoTen");
					this.OnhoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tuoi", DbType="Int")]
		public System.Nullable<int> tuoi
		{
			get
			{
				return this._tuoi;
			}
			set
			{
				if ((this._tuoi != value))
				{
					this.OntuoiChanging(value);
					this.SendPropertyChanging();
					this._tuoi = value;
					this.SendPropertyChanged("tuoi");
					this.OntuoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(500)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dienThoai", DbType="NVarChar(50)")]
		public string dienThoai
		{
			get
			{
				return this._dienThoai;
			}
			set
			{
				if ((this._dienThoai != value))
				{
					this.OndienThoaiChanging(value);
					this.SendPropertyChanging();
					this._dienThoai = value;
					this.SendPropertyChanged("dienThoai");
					this.OndienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BenhNhan_HoaDonXuat", Storage="_HoaDonXuats", ThisKey="idBN", OtherKey="idBN")]
		public EntitySet<HoaDonXuat> HoaDonXuats
		{
			get
			{
				return this._HoaDonXuats;
			}
			set
			{
				this._HoaDonXuats.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDonXuats(HoaDonXuat entity)
		{
			this.SendPropertyChanging();
			entity.BenhNhan = this;
		}
		
		private void detach_HoaDonXuats(HoaDonXuat entity)
		{
			this.SendPropertyChanging();
			entity.BenhNhan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Thuoc")]
	public partial class Thuoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _iDThuoc;
		
		private string _maThuoc;
		
		private string _tenThuoc;
		
		private string _maNhom;
		
		private string _nguonGoc;
		
		private string _maNSX;
		
		private System.Nullable<int> _soLuong;
		
		private System.Nullable<double> _giaBan;
		
		private string _maDVT;
		
		private string _thanhPhan;
		
		private string _hamluong;
		
		private string _congDung;
		
		private string _phanTacDung;
		
		private string _cachDung;
		
		private string _chuY;
		
		private string _hanSuDung;
		
		private string _baoQuan;
		
		private string _dangBaoChe;
		
		private EntitySet<chiTietHoaDonNhap> _chiTietHoaDonNhaps;
		
		private EntitySet<chiTietHoaDonXuat> _chiTietHoaDonXuats;
		
		private EntityRef<DonViTinh> _DonViTinh;
		
		private EntityRef<NhaSanXuat> _NhaSanXuat;
		
		private EntityRef<NhomThuoc> _NhomThuoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OniDThuocChanging(string value);
    partial void OniDThuocChanged();
    partial void OnmaThuocChanging(string value);
    partial void OnmaThuocChanged();
    partial void OntenThuocChanging(string value);
    partial void OntenThuocChanged();
    partial void OnmaNhomChanging(string value);
    partial void OnmaNhomChanged();
    partial void OnnguonGocChanging(string value);
    partial void OnnguonGocChanged();
    partial void OnmaNSXChanging(string value);
    partial void OnmaNSXChanged();
    partial void OnsoLuongChanging(System.Nullable<int> value);
    partial void OnsoLuongChanged();
    partial void OngiaBanChanging(System.Nullable<double> value);
    partial void OngiaBanChanged();
    partial void OnmaDVTChanging(string value);
    partial void OnmaDVTChanged();
    partial void OnthanhPhanChanging(string value);
    partial void OnthanhPhanChanged();
    partial void OnhamluongChanging(string value);
    partial void OnhamluongChanged();
    partial void OncongDungChanging(string value);
    partial void OncongDungChanged();
    partial void OnphanTacDungChanging(string value);
    partial void OnphanTacDungChanged();
    partial void OncachDungChanging(string value);
    partial void OncachDungChanged();
    partial void OnchuYChanging(string value);
    partial void OnchuYChanged();
    partial void OnhanSuDungChanging(string value);
    partial void OnhanSuDungChanged();
    partial void OnbaoQuanChanging(string value);
    partial void OnbaoQuanChanged();
    partial void OndangBaoCheChanging(string value);
    partial void OndangBaoCheChanged();
    #endregion
		
		public Thuoc()
		{
			this._chiTietHoaDonNhaps = new EntitySet<chiTietHoaDonNhap>(new Action<chiTietHoaDonNhap>(this.attach_chiTietHoaDonNhaps), new Action<chiTietHoaDonNhap>(this.detach_chiTietHoaDonNhaps));
			this._chiTietHoaDonXuats = new EntitySet<chiTietHoaDonXuat>(new Action<chiTietHoaDonXuat>(this.attach_chiTietHoaDonXuats), new Action<chiTietHoaDonXuat>(this.detach_chiTietHoaDonXuats));
			this._DonViTinh = default(EntityRef<DonViTinh>);
			this._NhaSanXuat = default(EntityRef<NhaSanXuat>);
			this._NhomThuoc = default(EntityRef<NhomThuoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iDThuoc", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string iDThuoc
		{
			get
			{
				return this._iDThuoc;
			}
			set
			{
				if ((this._iDThuoc != value))
				{
					this.OniDThuocChanging(value);
					this.SendPropertyChanging();
					this._iDThuoc = value;
					this.SendPropertyChanged("iDThuoc");
					this.OniDThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maThuoc", DbType="NVarChar(100)")]
		public string maThuoc
		{
			get
			{
				return this._maThuoc;
			}
			set
			{
				if ((this._maThuoc != value))
				{
					this.OnmaThuocChanging(value);
					this.SendPropertyChanging();
					this._maThuoc = value;
					this.SendPropertyChanged("maThuoc");
					this.OnmaThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenThuoc", DbType="NVarChar(50)")]
		public string tenThuoc
		{
			get
			{
				return this._tenThuoc;
			}
			set
			{
				if ((this._tenThuoc != value))
				{
					this.OntenThuocChanging(value);
					this.SendPropertyChanging();
					this._tenThuoc = value;
					this.SendPropertyChanged("tenThuoc");
					this.OntenThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhom", DbType="VarChar(50)")]
		public string maNhom
		{
			get
			{
				return this._maNhom;
			}
			set
			{
				if ((this._maNhom != value))
				{
					if (this._NhomThuoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNhomChanging(value);
					this.SendPropertyChanging();
					this._maNhom = value;
					this.SendPropertyChanged("maNhom");
					this.OnmaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguonGoc", DbType="NVarChar(100)")]
		public string nguonGoc
		{
			get
			{
				return this._nguonGoc;
			}
			set
			{
				if ((this._nguonGoc != value))
				{
					this.OnnguonGocChanging(value);
					this.SendPropertyChanging();
					this._nguonGoc = value;
					this.SendPropertyChanged("nguonGoc");
					this.OnnguonGocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNSX", DbType="VarChar(50)")]
		public string maNSX
		{
			get
			{
				return this._maNSX;
			}
			set
			{
				if ((this._maNSX != value))
				{
					if (this._NhaSanXuat.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNSXChanging(value);
					this.SendPropertyChanging();
					this._maNSX = value;
					this.SendPropertyChanged("maNSX");
					this.OnmaNSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int")]
		public System.Nullable<int> soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this.OnsoLuongChanging(value);
					this.SendPropertyChanging();
					this._soLuong = value;
					this.SendPropertyChanged("soLuong");
					this.OnsoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaBan", DbType="Float")]
		public System.Nullable<double> giaBan
		{
			get
			{
				return this._giaBan;
			}
			set
			{
				if ((this._giaBan != value))
				{
					this.OngiaBanChanging(value);
					this.SendPropertyChanging();
					this._giaBan = value;
					this.SendPropertyChanged("giaBan");
					this.OngiaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDVT", DbType="VarChar(50)")]
		public string maDVT
		{
			get
			{
				return this._maDVT;
			}
			set
			{
				if ((this._maDVT != value))
				{
					if (this._DonViTinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaDVTChanging(value);
					this.SendPropertyChanging();
					this._maDVT = value;
					this.SendPropertyChanged("maDVT");
					this.OnmaDVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanhPhan", DbType="NVarChar(500)")]
		public string thanhPhan
		{
			get
			{
				return this._thanhPhan;
			}
			set
			{
				if ((this._thanhPhan != value))
				{
					this.OnthanhPhanChanging(value);
					this.SendPropertyChanging();
					this._thanhPhan = value;
					this.SendPropertyChanged("thanhPhan");
					this.OnthanhPhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hamluong", DbType="NVarChar(500)")]
		public string hamluong
		{
			get
			{
				return this._hamluong;
			}
			set
			{
				if ((this._hamluong != value))
				{
					this.OnhamluongChanging(value);
					this.SendPropertyChanging();
					this._hamluong = value;
					this.SendPropertyChanged("hamluong");
					this.OnhamluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_congDung", DbType="NVarChar(500)")]
		public string congDung
		{
			get
			{
				return this._congDung;
			}
			set
			{
				if ((this._congDung != value))
				{
					this.OncongDungChanging(value);
					this.SendPropertyChanging();
					this._congDung = value;
					this.SendPropertyChanged("congDung");
					this.OncongDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phanTacDung", DbType="NVarChar(500)")]
		public string phanTacDung
		{
			get
			{
				return this._phanTacDung;
			}
			set
			{
				if ((this._phanTacDung != value))
				{
					this.OnphanTacDungChanging(value);
					this.SendPropertyChanging();
					this._phanTacDung = value;
					this.SendPropertyChanged("phanTacDung");
					this.OnphanTacDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cachDung", DbType="NVarChar(500)")]
		public string cachDung
		{
			get
			{
				return this._cachDung;
			}
			set
			{
				if ((this._cachDung != value))
				{
					this.OncachDungChanging(value);
					this.SendPropertyChanging();
					this._cachDung = value;
					this.SendPropertyChanged("cachDung");
					this.OncachDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chuY", DbType="NVarChar(500)")]
		public string chuY
		{
			get
			{
				return this._chuY;
			}
			set
			{
				if ((this._chuY != value))
				{
					this.OnchuYChanging(value);
					this.SendPropertyChanging();
					this._chuY = value;
					this.SendPropertyChanged("chuY");
					this.OnchuYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hanSuDung", DbType="NVarChar(500)")]
		public string hanSuDung
		{
			get
			{
				return this._hanSuDung;
			}
			set
			{
				if ((this._hanSuDung != value))
				{
					this.OnhanSuDungChanging(value);
					this.SendPropertyChanging();
					this._hanSuDung = value;
					this.SendPropertyChanged("hanSuDung");
					this.OnhanSuDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_baoQuan", DbType="NVarChar(500)")]
		public string baoQuan
		{
			get
			{
				return this._baoQuan;
			}
			set
			{
				if ((this._baoQuan != value))
				{
					this.OnbaoQuanChanging(value);
					this.SendPropertyChanging();
					this._baoQuan = value;
					this.SendPropertyChanged("baoQuan");
					this.OnbaoQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dangBaoChe", DbType="NVarChar(500)")]
		public string dangBaoChe
		{
			get
			{
				return this._dangBaoChe;
			}
			set
			{
				if ((this._dangBaoChe != value))
				{
					this.OndangBaoCheChanging(value);
					this.SendPropertyChanging();
					this._dangBaoChe = value;
					this.SendPropertyChanged("dangBaoChe");
					this.OndangBaoCheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thuoc_chiTietHoaDonNhap", Storage="_chiTietHoaDonNhaps", ThisKey="iDThuoc", OtherKey="idThuoc")]
		public EntitySet<chiTietHoaDonNhap> chiTietHoaDonNhaps
		{
			get
			{
				return this._chiTietHoaDonNhaps;
			}
			set
			{
				this._chiTietHoaDonNhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thuoc_chiTietHoaDonXuat", Storage="_chiTietHoaDonXuats", ThisKey="iDThuoc", OtherKey="idThuoc")]
		public EntitySet<chiTietHoaDonXuat> chiTietHoaDonXuats
		{
			get
			{
				return this._chiTietHoaDonXuats;
			}
			set
			{
				this._chiTietHoaDonXuats.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonViTinh_Thuoc", Storage="_DonViTinh", ThisKey="maDVT", OtherKey="maDVT", IsForeignKey=true)]
		public DonViTinh DonViTinh
		{
			get
			{
				return this._DonViTinh.Entity;
			}
			set
			{
				DonViTinh previousValue = this._DonViTinh.Entity;
				if (((previousValue != value) 
							|| (this._DonViTinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DonViTinh.Entity = null;
						previousValue.Thuocs.Remove(this);
					}
					this._DonViTinh.Entity = value;
					if ((value != null))
					{
						value.Thuocs.Add(this);
						this._maDVT = value.maDVT;
					}
					else
					{
						this._maDVT = default(string);
					}
					this.SendPropertyChanged("DonViTinh");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaSanXuat_Thuoc", Storage="_NhaSanXuat", ThisKey="maNSX", OtherKey="maNSX", IsForeignKey=true)]
		public NhaSanXuat NhaSanXuat
		{
			get
			{
				return this._NhaSanXuat.Entity;
			}
			set
			{
				NhaSanXuat previousValue = this._NhaSanXuat.Entity;
				if (((previousValue != value) 
							|| (this._NhaSanXuat.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhaSanXuat.Entity = null;
						previousValue.Thuocs.Remove(this);
					}
					this._NhaSanXuat.Entity = value;
					if ((value != null))
					{
						value.Thuocs.Add(this);
						this._maNSX = value.maNSX;
					}
					else
					{
						this._maNSX = default(string);
					}
					this.SendPropertyChanged("NhaSanXuat");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomThuoc_Thuoc", Storage="_NhomThuoc", ThisKey="maNhom", OtherKey="maNhom", IsForeignKey=true)]
		public NhomThuoc NhomThuoc
		{
			get
			{
				return this._NhomThuoc.Entity;
			}
			set
			{
				NhomThuoc previousValue = this._NhomThuoc.Entity;
				if (((previousValue != value) 
							|| (this._NhomThuoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhomThuoc.Entity = null;
						previousValue.Thuocs.Remove(this);
					}
					this._NhomThuoc.Entity = value;
					if ((value != null))
					{
						value.Thuocs.Add(this);
						this._maNhom = value.maNhom;
					}
					else
					{
						this._maNhom = default(string);
					}
					this.SendPropertyChanged("NhomThuoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chiTietHoaDonNhaps(chiTietHoaDonNhap entity)
		{
			this.SendPropertyChanging();
			entity.Thuoc = this;
		}
		
		private void detach_chiTietHoaDonNhaps(chiTietHoaDonNhap entity)
		{
			this.SendPropertyChanging();
			entity.Thuoc = null;
		}
		
		private void attach_chiTietHoaDonXuats(chiTietHoaDonXuat entity)
		{
			this.SendPropertyChanging();
			entity.Thuoc = this;
		}
		
		private void detach_chiTietHoaDonXuats(chiTietHoaDonXuat entity)
		{
			this.SendPropertyChanging();
			entity.Thuoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chiTietHoaDonNhap")]
	public partial class chiTietHoaDonNhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maCTHDN;
		
		private string _maHDN;
		
		private string _idThuoc;
		
		private System.Nullable<int> _soLuong;
		
		private System.Nullable<double> _giaNhap;
		
		private EntityRef<Thuoc> _Thuoc;
		
		private EntityRef<HoaDonNhap> _HoaDonNhap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaCTHDNChanging(string value);
    partial void OnmaCTHDNChanged();
    partial void OnmaHDNChanging(string value);
    partial void OnmaHDNChanged();
    partial void OnidThuocChanging(string value);
    partial void OnidThuocChanged();
    partial void OnsoLuongChanging(System.Nullable<int> value);
    partial void OnsoLuongChanged();
    partial void OngiaNhapChanging(System.Nullable<double> value);
    partial void OngiaNhapChanged();
    #endregion
		
		public chiTietHoaDonNhap()
		{
			this._Thuoc = default(EntityRef<Thuoc>);
			this._HoaDonNhap = default(EntityRef<HoaDonNhap>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCTHDN", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maCTHDN
		{
			get
			{
				return this._maCTHDN;
			}
			set
			{
				if ((this._maCTHDN != value))
				{
					this.OnmaCTHDNChanging(value);
					this.SendPropertyChanging();
					this._maCTHDN = value;
					this.SendPropertyChanged("maCTHDN");
					this.OnmaCTHDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHDN", DbType="VarChar(50)")]
		public string maHDN
		{
			get
			{
				return this._maHDN;
			}
			set
			{
				if ((this._maHDN != value))
				{
					if (this._HoaDonNhap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaHDNChanging(value);
					this.SendPropertyChanging();
					this._maHDN = value;
					this.SendPropertyChanged("maHDN");
					this.OnmaHDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idThuoc", DbType="VarChar(50)")]
		public string idThuoc
		{
			get
			{
				return this._idThuoc;
			}
			set
			{
				if ((this._idThuoc != value))
				{
					if (this._Thuoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidThuocChanging(value);
					this.SendPropertyChanging();
					this._idThuoc = value;
					this.SendPropertyChanged("idThuoc");
					this.OnidThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int")]
		public System.Nullable<int> soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this.OnsoLuongChanging(value);
					this.SendPropertyChanging();
					this._soLuong = value;
					this.SendPropertyChanged("soLuong");
					this.OnsoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaNhap", DbType="Float")]
		public System.Nullable<double> giaNhap
		{
			get
			{
				return this._giaNhap;
			}
			set
			{
				if ((this._giaNhap != value))
				{
					this.OngiaNhapChanging(value);
					this.SendPropertyChanging();
					this._giaNhap = value;
					this.SendPropertyChanged("giaNhap");
					this.OngiaNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thuoc_chiTietHoaDonNhap", Storage="_Thuoc", ThisKey="idThuoc", OtherKey="iDThuoc", IsForeignKey=true)]
		public Thuoc Thuoc
		{
			get
			{
				return this._Thuoc.Entity;
			}
			set
			{
				Thuoc previousValue = this._Thuoc.Entity;
				if (((previousValue != value) 
							|| (this._Thuoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Thuoc.Entity = null;
						previousValue.chiTietHoaDonNhaps.Remove(this);
					}
					this._Thuoc.Entity = value;
					if ((value != null))
					{
						value.chiTietHoaDonNhaps.Add(this);
						this._idThuoc = value.iDThuoc;
					}
					else
					{
						this._idThuoc = default(string);
					}
					this.SendPropertyChanged("Thuoc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDonNhap_chiTietHoaDonNhap", Storage="_HoaDonNhap", ThisKey="maHDN", OtherKey="maHDN", IsForeignKey=true)]
		public HoaDonNhap HoaDonNhap
		{
			get
			{
				return this._HoaDonNhap.Entity;
			}
			set
			{
				HoaDonNhap previousValue = this._HoaDonNhap.Entity;
				if (((previousValue != value) 
							|| (this._HoaDonNhap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoaDonNhap.Entity = null;
						previousValue.chiTietHoaDonNhaps.Remove(this);
					}
					this._HoaDonNhap.Entity = value;
					if ((value != null))
					{
						value.chiTietHoaDonNhaps.Add(this);
						this._maHDN = value.maHDN;
					}
					else
					{
						this._maHDN = default(string);
					}
					this.SendPropertyChanged("HoaDonNhap");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chiTietHoaDonXuat")]
	public partial class chiTietHoaDonXuat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maCTHDX;
		
		private string _maHDX;
		
		private string _idThuoc;
		
		private System.Nullable<int> _soLuong;
		
		private System.Nullable<double> _giaBan;
		
		private System.Nullable<double> _thue;
		
		private string _donVi;
		
		private EntityRef<Thuoc> _Thuoc;
		
		private EntityRef<HoaDonXuat> _HoaDonXuat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaCTHDXChanging(string value);
    partial void OnmaCTHDXChanged();
    partial void OnmaHDXChanging(string value);
    partial void OnmaHDXChanged();
    partial void OnidThuocChanging(string value);
    partial void OnidThuocChanged();
    partial void OnsoLuongChanging(System.Nullable<int> value);
    partial void OnsoLuongChanged();
    partial void OngiaBanChanging(System.Nullable<double> value);
    partial void OngiaBanChanged();
    partial void OnthueChanging(System.Nullable<double> value);
    partial void OnthueChanged();
    partial void OndonViChanging(string value);
    partial void OndonViChanged();
    #endregion
		
		public chiTietHoaDonXuat()
		{
			this._Thuoc = default(EntityRef<Thuoc>);
			this._HoaDonXuat = default(EntityRef<HoaDonXuat>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCTHDX", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maCTHDX
		{
			get
			{
				return this._maCTHDX;
			}
			set
			{
				if ((this._maCTHDX != value))
				{
					this.OnmaCTHDXChanging(value);
					this.SendPropertyChanging();
					this._maCTHDX = value;
					this.SendPropertyChanged("maCTHDX");
					this.OnmaCTHDXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHDX", DbType="VarChar(50)")]
		public string maHDX
		{
			get
			{
				return this._maHDX;
			}
			set
			{
				if ((this._maHDX != value))
				{
					if (this._HoaDonXuat.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaHDXChanging(value);
					this.SendPropertyChanging();
					this._maHDX = value;
					this.SendPropertyChanged("maHDX");
					this.OnmaHDXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idThuoc", DbType="VarChar(50)")]
		public string idThuoc
		{
			get
			{
				return this._idThuoc;
			}
			set
			{
				if ((this._idThuoc != value))
				{
					if (this._Thuoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidThuocChanging(value);
					this.SendPropertyChanging();
					this._idThuoc = value;
					this.SendPropertyChanged("idThuoc");
					this.OnidThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int")]
		public System.Nullable<int> soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this.OnsoLuongChanging(value);
					this.SendPropertyChanging();
					this._soLuong = value;
					this.SendPropertyChanged("soLuong");
					this.OnsoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaBan", DbType="Float")]
		public System.Nullable<double> giaBan
		{
			get
			{
				return this._giaBan;
			}
			set
			{
				if ((this._giaBan != value))
				{
					this.OngiaBanChanging(value);
					this.SendPropertyChanging();
					this._giaBan = value;
					this.SendPropertyChanged("giaBan");
					this.OngiaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thue", DbType="Float")]
		public System.Nullable<double> thue
		{
			get
			{
				return this._thue;
			}
			set
			{
				if ((this._thue != value))
				{
					this.OnthueChanging(value);
					this.SendPropertyChanging();
					this._thue = value;
					this.SendPropertyChanged("thue");
					this.OnthueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donVi", DbType="NVarChar(50)")]
		public string donVi
		{
			get
			{
				return this._donVi;
			}
			set
			{
				if ((this._donVi != value))
				{
					this.OndonViChanging(value);
					this.SendPropertyChanging();
					this._donVi = value;
					this.SendPropertyChanged("donVi");
					this.OndonViChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thuoc_chiTietHoaDonXuat", Storage="_Thuoc", ThisKey="idThuoc", OtherKey="iDThuoc", IsForeignKey=true)]
		public Thuoc Thuoc
		{
			get
			{
				return this._Thuoc.Entity;
			}
			set
			{
				Thuoc previousValue = this._Thuoc.Entity;
				if (((previousValue != value) 
							|| (this._Thuoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Thuoc.Entity = null;
						previousValue.chiTietHoaDonXuats.Remove(this);
					}
					this._Thuoc.Entity = value;
					if ((value != null))
					{
						value.chiTietHoaDonXuats.Add(this);
						this._idThuoc = value.iDThuoc;
					}
					else
					{
						this._idThuoc = default(string);
					}
					this.SendPropertyChanged("Thuoc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDonXuat_chiTietHoaDonXuat", Storage="_HoaDonXuat", ThisKey="maHDX", OtherKey="maHDX", IsForeignKey=true)]
		public HoaDonXuat HoaDonXuat
		{
			get
			{
				return this._HoaDonXuat.Entity;
			}
			set
			{
				HoaDonXuat previousValue = this._HoaDonXuat.Entity;
				if (((previousValue != value) 
							|| (this._HoaDonXuat.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoaDonXuat.Entity = null;
						previousValue.chiTietHoaDonXuats.Remove(this);
					}
					this._HoaDonXuat.Entity = value;
					if ((value != null))
					{
						value.chiTietHoaDonXuats.Add(this);
						this._maHDX = value.maHDX;
					}
					else
					{
						this._maHDX = default(string);
					}
					this.SendPropertyChanged("HoaDonXuat");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DonViTinh")]
	public partial class DonViTinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maDVT;
		
		private string _tenDVT;
		
		private EntitySet<Thuoc> _Thuocs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaDVTChanging(string value);
    partial void OnmaDVTChanged();
    partial void OntenDVTChanging(string value);
    partial void OntenDVTChanged();
    #endregion
		
		public DonViTinh()
		{
			this._Thuocs = new EntitySet<Thuoc>(new Action<Thuoc>(this.attach_Thuocs), new Action<Thuoc>(this.detach_Thuocs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDVT", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maDVT
		{
			get
			{
				return this._maDVT;
			}
			set
			{
				if ((this._maDVT != value))
				{
					this.OnmaDVTChanging(value);
					this.SendPropertyChanging();
					this._maDVT = value;
					this.SendPropertyChanged("maDVT");
					this.OnmaDVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenDVT", DbType="NVarChar(50)")]
		public string tenDVT
		{
			get
			{
				return this._tenDVT;
			}
			set
			{
				if ((this._tenDVT != value))
				{
					this.OntenDVTChanging(value);
					this.SendPropertyChanging();
					this._tenDVT = value;
					this.SendPropertyChanged("tenDVT");
					this.OntenDVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonViTinh_Thuoc", Storage="_Thuocs", ThisKey="maDVT", OtherKey="maDVT")]
		public EntitySet<Thuoc> Thuocs
		{
			get
			{
				return this._Thuocs;
			}
			set
			{
				this._Thuocs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Thuocs(Thuoc entity)
		{
			this.SendPropertyChanging();
			entity.DonViTinh = this;
		}
		
		private void detach_Thuocs(Thuoc entity)
		{
			this.SendPropertyChanging();
			entity.DonViTinh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDonNhap")]
	public partial class HoaDonNhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maHDN;
		
		private string _maNPP;
		
		private string _nguoiGiao;
		
		private string _nguoiNhan;
		
		private System.Nullable<double> _tongTienThuoc;
		
		private System.Nullable<double> _tongThue;
		
		private System.Nullable<double> _tongTienHD;
		
		private System.Nullable<System.DateTime> _ngayViet;
		
		private System.Nullable<System.DateTime> _ngayNhap;
		
		private EntitySet<chiTietHoaDonNhap> _chiTietHoaDonNhaps;
		
		private EntityRef<NhaPhanPhoi> _NhaPhanPhoi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHDNChanging(string value);
    partial void OnmaHDNChanged();
    partial void OnmaNPPChanging(string value);
    partial void OnmaNPPChanged();
    partial void OnnguoiGiaoChanging(string value);
    partial void OnnguoiGiaoChanged();
    partial void OnnguoiNhanChanging(string value);
    partial void OnnguoiNhanChanged();
    partial void OntongTienThuocChanging(System.Nullable<double> value);
    partial void OntongTienThuocChanged();
    partial void OntongThueChanging(System.Nullable<double> value);
    partial void OntongThueChanged();
    partial void OntongTienHDChanging(System.Nullable<double> value);
    partial void OntongTienHDChanged();
    partial void OnngayVietChanging(System.Nullable<System.DateTime> value);
    partial void OnngayVietChanged();
    partial void OnngayNhapChanging(System.Nullable<System.DateTime> value);
    partial void OnngayNhapChanged();
    #endregion
		
		public HoaDonNhap()
		{
			this._chiTietHoaDonNhaps = new EntitySet<chiTietHoaDonNhap>(new Action<chiTietHoaDonNhap>(this.attach_chiTietHoaDonNhaps), new Action<chiTietHoaDonNhap>(this.detach_chiTietHoaDonNhaps));
			this._NhaPhanPhoi = default(EntityRef<NhaPhanPhoi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHDN", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHDN
		{
			get
			{
				return this._maHDN;
			}
			set
			{
				if ((this._maHDN != value))
				{
					this.OnmaHDNChanging(value);
					this.SendPropertyChanging();
					this._maHDN = value;
					this.SendPropertyChanged("maHDN");
					this.OnmaHDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNPP", DbType="VarChar(50)")]
		public string maNPP
		{
			get
			{
				return this._maNPP;
			}
			set
			{
				if ((this._maNPP != value))
				{
					if (this._NhaPhanPhoi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNPPChanging(value);
					this.SendPropertyChanging();
					this._maNPP = value;
					this.SendPropertyChanged("maNPP");
					this.OnmaNPPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoiGiao", DbType="NVarChar(50)")]
		public string nguoiGiao
		{
			get
			{
				return this._nguoiGiao;
			}
			set
			{
				if ((this._nguoiGiao != value))
				{
					this.OnnguoiGiaoChanging(value);
					this.SendPropertyChanging();
					this._nguoiGiao = value;
					this.SendPropertyChanged("nguoiGiao");
					this.OnnguoiGiaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoiNhan", DbType="NVarChar(50)")]
		public string nguoiNhan
		{
			get
			{
				return this._nguoiNhan;
			}
			set
			{
				if ((this._nguoiNhan != value))
				{
					this.OnnguoiNhanChanging(value);
					this.SendPropertyChanging();
					this._nguoiNhan = value;
					this.SendPropertyChanged("nguoiNhan");
					this.OnnguoiNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongTienThuoc", DbType="Float")]
		public System.Nullable<double> tongTienThuoc
		{
			get
			{
				return this._tongTienThuoc;
			}
			set
			{
				if ((this._tongTienThuoc != value))
				{
					this.OntongTienThuocChanging(value);
					this.SendPropertyChanging();
					this._tongTienThuoc = value;
					this.SendPropertyChanged("tongTienThuoc");
					this.OntongTienThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongThue", DbType="Float")]
		public System.Nullable<double> tongThue
		{
			get
			{
				return this._tongThue;
			}
			set
			{
				if ((this._tongThue != value))
				{
					this.OntongThueChanging(value);
					this.SendPropertyChanging();
					this._tongThue = value;
					this.SendPropertyChanged("tongThue");
					this.OntongThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongTienHD", DbType="Float")]
		public System.Nullable<double> tongTienHD
		{
			get
			{
				return this._tongTienHD;
			}
			set
			{
				if ((this._tongTienHD != value))
				{
					this.OntongTienHDChanging(value);
					this.SendPropertyChanging();
					this._tongTienHD = value;
					this.SendPropertyChanged("tongTienHD");
					this.OntongTienHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayViet", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayViet
		{
			get
			{
				return this._ngayViet;
			}
			set
			{
				if ((this._ngayViet != value))
				{
					this.OnngayVietChanging(value);
					this.SendPropertyChanging();
					this._ngayViet = value;
					this.SendPropertyChanged("ngayViet");
					this.OnngayVietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayNhap", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayNhap
		{
			get
			{
				return this._ngayNhap;
			}
			set
			{
				if ((this._ngayNhap != value))
				{
					this.OnngayNhapChanging(value);
					this.SendPropertyChanging();
					this._ngayNhap = value;
					this.SendPropertyChanged("ngayNhap");
					this.OnngayNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDonNhap_chiTietHoaDonNhap", Storage="_chiTietHoaDonNhaps", ThisKey="maHDN", OtherKey="maHDN")]
		public EntitySet<chiTietHoaDonNhap> chiTietHoaDonNhaps
		{
			get
			{
				return this._chiTietHoaDonNhaps;
			}
			set
			{
				this._chiTietHoaDonNhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaPhanPhoi_HoaDonNhap", Storage="_NhaPhanPhoi", ThisKey="maNPP", OtherKey="maNPP", IsForeignKey=true)]
		public NhaPhanPhoi NhaPhanPhoi
		{
			get
			{
				return this._NhaPhanPhoi.Entity;
			}
			set
			{
				NhaPhanPhoi previousValue = this._NhaPhanPhoi.Entity;
				if (((previousValue != value) 
							|| (this._NhaPhanPhoi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhaPhanPhoi.Entity = null;
						previousValue.HoaDonNhaps.Remove(this);
					}
					this._NhaPhanPhoi.Entity = value;
					if ((value != null))
					{
						value.HoaDonNhaps.Add(this);
						this._maNPP = value.maNPP;
					}
					else
					{
						this._maNPP = default(string);
					}
					this.SendPropertyChanged("NhaPhanPhoi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chiTietHoaDonNhaps(chiTietHoaDonNhap entity)
		{
			this.SendPropertyChanging();
			entity.HoaDonNhap = this;
		}
		
		private void detach_chiTietHoaDonNhaps(chiTietHoaDonNhap entity)
		{
			this.SendPropertyChanging();
			entity.HoaDonNhap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDonXuat")]
	public partial class HoaDonXuat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maHDX;
		
		private string _idBN;
		
		private System.Nullable<double> _tongTienThuoc;
		
		private System.Nullable<System.DateTime> _ngayLap;
		
		private System.Nullable<double> _tongThue;
		
		private System.Nullable<double> _tongTienHD;
		
		private EntitySet<chiTietHoaDonXuat> _chiTietHoaDonXuats;
		
		private EntityRef<BenhNhan> _BenhNhan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHDXChanging(string value);
    partial void OnmaHDXChanged();
    partial void OnidBNChanging(string value);
    partial void OnidBNChanged();
    partial void OntongTienThuocChanging(System.Nullable<double> value);
    partial void OntongTienThuocChanged();
    partial void OnngayLapChanging(System.Nullable<System.DateTime> value);
    partial void OnngayLapChanged();
    partial void OntongThueChanging(System.Nullable<double> value);
    partial void OntongThueChanged();
    partial void OntongTienHDChanging(System.Nullable<double> value);
    partial void OntongTienHDChanged();
    #endregion
		
		public HoaDonXuat()
		{
			this._chiTietHoaDonXuats = new EntitySet<chiTietHoaDonXuat>(new Action<chiTietHoaDonXuat>(this.attach_chiTietHoaDonXuats), new Action<chiTietHoaDonXuat>(this.detach_chiTietHoaDonXuats));
			this._BenhNhan = default(EntityRef<BenhNhan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHDX", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHDX
		{
			get
			{
				return this._maHDX;
			}
			set
			{
				if ((this._maHDX != value))
				{
					this.OnmaHDXChanging(value);
					this.SendPropertyChanging();
					this._maHDX = value;
					this.SendPropertyChanged("maHDX");
					this.OnmaHDXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idBN", DbType="VarChar(50)")]
		public string idBN
		{
			get
			{
				return this._idBN;
			}
			set
			{
				if ((this._idBN != value))
				{
					if (this._BenhNhan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidBNChanging(value);
					this.SendPropertyChanging();
					this._idBN = value;
					this.SendPropertyChanged("idBN");
					this.OnidBNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongTienThuoc", DbType="Float")]
		public System.Nullable<double> tongTienThuoc
		{
			get
			{
				return this._tongTienThuoc;
			}
			set
			{
				if ((this._tongTienThuoc != value))
				{
					this.OntongTienThuocChanging(value);
					this.SendPropertyChanging();
					this._tongTienThuoc = value;
					this.SendPropertyChanged("tongTienThuoc");
					this.OntongTienThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayLap", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayLap
		{
			get
			{
				return this._ngayLap;
			}
			set
			{
				if ((this._ngayLap != value))
				{
					this.OnngayLapChanging(value);
					this.SendPropertyChanging();
					this._ngayLap = value;
					this.SendPropertyChanged("ngayLap");
					this.OnngayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongThue", DbType="Float")]
		public System.Nullable<double> tongThue
		{
			get
			{
				return this._tongThue;
			}
			set
			{
				if ((this._tongThue != value))
				{
					this.OntongThueChanging(value);
					this.SendPropertyChanging();
					this._tongThue = value;
					this.SendPropertyChanged("tongThue");
					this.OntongThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongTienHD", DbType="Float")]
		public System.Nullable<double> tongTienHD
		{
			get
			{
				return this._tongTienHD;
			}
			set
			{
				if ((this._tongTienHD != value))
				{
					this.OntongTienHDChanging(value);
					this.SendPropertyChanging();
					this._tongTienHD = value;
					this.SendPropertyChanged("tongTienHD");
					this.OntongTienHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDonXuat_chiTietHoaDonXuat", Storage="_chiTietHoaDonXuats", ThisKey="maHDX", OtherKey="maHDX")]
		public EntitySet<chiTietHoaDonXuat> chiTietHoaDonXuats
		{
			get
			{
				return this._chiTietHoaDonXuats;
			}
			set
			{
				this._chiTietHoaDonXuats.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BenhNhan_HoaDonXuat", Storage="_BenhNhan", ThisKey="idBN", OtherKey="idBN", IsForeignKey=true)]
		public BenhNhan BenhNhan
		{
			get
			{
				return this._BenhNhan.Entity;
			}
			set
			{
				BenhNhan previousValue = this._BenhNhan.Entity;
				if (((previousValue != value) 
							|| (this._BenhNhan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BenhNhan.Entity = null;
						previousValue.HoaDonXuats.Remove(this);
					}
					this._BenhNhan.Entity = value;
					if ((value != null))
					{
						value.HoaDonXuats.Add(this);
						this._idBN = value.idBN;
					}
					else
					{
						this._idBN = default(string);
					}
					this.SendPropertyChanged("BenhNhan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chiTietHoaDonXuats(chiTietHoaDonXuat entity)
		{
			this.SendPropertyChanging();
			entity.HoaDonXuat = this;
		}
		
		private void detach_chiTietHoaDonXuats(chiTietHoaDonXuat entity)
		{
			this.SendPropertyChanging();
			entity.HoaDonXuat = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhaPhanPhoi")]
	public partial class NhaPhanPhoi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maNPP;
		
		private string _tenNPP;
		
		private string _diaChi;
		
		private string _dienThoai;
		
		private string _email;
		
		private string _maSoThue;
		
		private string _ghiChu;
		
		private EntitySet<HoaDonNhap> _HoaDonNhaps;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNPPChanging(string value);
    partial void OnmaNPPChanged();
    partial void OntenNPPChanging(string value);
    partial void OntenNPPChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OndienThoaiChanging(string value);
    partial void OndienThoaiChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnmaSoThueChanging(string value);
    partial void OnmaSoThueChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    #endregion
		
		public NhaPhanPhoi()
		{
			this._HoaDonNhaps = new EntitySet<HoaDonNhap>(new Action<HoaDonNhap>(this.attach_HoaDonNhaps), new Action<HoaDonNhap>(this.detach_HoaDonNhaps));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNPP", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maNPP
		{
			get
			{
				return this._maNPP;
			}
			set
			{
				if ((this._maNPP != value))
				{
					this.OnmaNPPChanging(value);
					this.SendPropertyChanging();
					this._maNPP = value;
					this.SendPropertyChanged("maNPP");
					this.OnmaNPPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNPP", DbType="NVarChar(100)")]
		public string tenNPP
		{
			get
			{
				return this._tenNPP;
			}
			set
			{
				if ((this._tenNPP != value))
				{
					this.OntenNPPChanging(value);
					this.SendPropertyChanging();
					this._tenNPP = value;
					this.SendPropertyChanged("tenNPP");
					this.OntenNPPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(200)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dienThoai", DbType="NVarChar(100)")]
		public string dienThoai
		{
			get
			{
				return this._dienThoai;
			}
			set
			{
				if ((this._dienThoai != value))
				{
					this.OndienThoaiChanging(value);
					this.SendPropertyChanging();
					this._dienThoai = value;
					this.SendPropertyChanged("dienThoai");
					this.OndienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSoThue", DbType="NVarChar(100)")]
		public string maSoThue
		{
			get
			{
				return this._maSoThue;
			}
			set
			{
				if ((this._maSoThue != value))
				{
					this.OnmaSoThueChanging(value);
					this.SendPropertyChanging();
					this._maSoThue = value;
					this.SendPropertyChanged("maSoThue");
					this.OnmaSoThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NVarChar(200)")]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaPhanPhoi_HoaDonNhap", Storage="_HoaDonNhaps", ThisKey="maNPP", OtherKey="maNPP")]
		public EntitySet<HoaDonNhap> HoaDonNhaps
		{
			get
			{
				return this._HoaDonNhaps;
			}
			set
			{
				this._HoaDonNhaps.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDonNhaps(HoaDonNhap entity)
		{
			this.SendPropertyChanging();
			entity.NhaPhanPhoi = this;
		}
		
		private void detach_HoaDonNhaps(HoaDonNhap entity)
		{
			this.SendPropertyChanging();
			entity.NhaPhanPhoi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhaSanXuat")]
	public partial class NhaSanXuat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maNSX;
		
		private string _tenNSX;
		
		private string _diaChi;
		
		private string _dienThoai;
		
		private string _email;
		
		private EntitySet<Thuoc> _Thuocs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNSXChanging(string value);
    partial void OnmaNSXChanged();
    partial void OntenNSXChanging(string value);
    partial void OntenNSXChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OndienThoaiChanging(string value);
    partial void OndienThoaiChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public NhaSanXuat()
		{
			this._Thuocs = new EntitySet<Thuoc>(new Action<Thuoc>(this.attach_Thuocs), new Action<Thuoc>(this.detach_Thuocs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNSX", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maNSX
		{
			get
			{
				return this._maNSX;
			}
			set
			{
				if ((this._maNSX != value))
				{
					this.OnmaNSXChanging(value);
					this.SendPropertyChanging();
					this._maNSX = value;
					this.SendPropertyChanged("maNSX");
					this.OnmaNSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNSX", DbType="NVarChar(100)")]
		public string tenNSX
		{
			get
			{
				return this._tenNSX;
			}
			set
			{
				if ((this._tenNSX != value))
				{
					this.OntenNSXChanging(value);
					this.SendPropertyChanging();
					this._tenNSX = value;
					this.SendPropertyChanged("tenNSX");
					this.OntenNSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(200)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dienThoai", DbType="NVarChar(100)")]
		public string dienThoai
		{
			get
			{
				return this._dienThoai;
			}
			set
			{
				if ((this._dienThoai != value))
				{
					this.OndienThoaiChanging(value);
					this.SendPropertyChanging();
					this._dienThoai = value;
					this.SendPropertyChanged("dienThoai");
					this.OndienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaSanXuat_Thuoc", Storage="_Thuocs", ThisKey="maNSX", OtherKey="maNSX")]
		public EntitySet<Thuoc> Thuocs
		{
			get
			{
				return this._Thuocs;
			}
			set
			{
				this._Thuocs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Thuocs(Thuoc entity)
		{
			this.SendPropertyChanging();
			entity.NhaSanXuat = this;
		}
		
		private void detach_Thuocs(Thuoc entity)
		{
			this.SendPropertyChanging();
			entity.NhaSanXuat = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhomThuoc")]
	public partial class NhomThuoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maNhom;
		
		private string _tenNhom;
		
		private string _ghiChu;
		
		private EntitySet<Thuoc> _Thuocs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNhomChanging(string value);
    partial void OnmaNhomChanged();
    partial void OntenNhomChanging(string value);
    partial void OntenNhomChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    #endregion
		
		public NhomThuoc()
		{
			this._Thuocs = new EntitySet<Thuoc>(new Action<Thuoc>(this.attach_Thuocs), new Action<Thuoc>(this.detach_Thuocs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhom", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maNhom
		{
			get
			{
				return this._maNhom;
			}
			set
			{
				if ((this._maNhom != value))
				{
					this.OnmaNhomChanging(value);
					this.SendPropertyChanging();
					this._maNhom = value;
					this.SendPropertyChanged("maNhom");
					this.OnmaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNhom", DbType="NVarChar(100)")]
		public string tenNhom
		{
			get
			{
				return this._tenNhom;
			}
			set
			{
				if ((this._tenNhom != value))
				{
					this.OntenNhomChanging(value);
					this.SendPropertyChanging();
					this._tenNhom = value;
					this.SendPropertyChanged("tenNhom");
					this.OntenNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NVarChar(100)")]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomThuoc_Thuoc", Storage="_Thuocs", ThisKey="maNhom", OtherKey="maNhom")]
		public EntitySet<Thuoc> Thuocs
		{
			get
			{
				return this._Thuocs;
			}
			set
			{
				this._Thuocs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Thuocs(Thuoc entity)
		{
			this.SendPropertyChanging();
			entity.NhomThuoc = this;
		}
		
		private void detach_Thuocs(Thuoc entity)
		{
			this.SendPropertyChanging();
			entity.NhomThuoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TaiKhoan1;
		
		private string _MatKhau;
		
		private string _HoTen;
		
		private System.Nullable<System.DateTime> _NgayTao;
		
		private string _ChucVu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTaiKhoan1Changing(string value);
    partial void OnTaiKhoan1Changed();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnNgayTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTaoChanged();
    partial void OnChucVuChanging(string value);
    partial void OnChucVuChanged();
    #endregion
		
		public TaiKhoan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="TaiKhoan", Storage="_TaiKhoan1", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TaiKhoan1
		{
			get
			{
				return this._TaiKhoan1;
			}
			set
			{
				if ((this._TaiKhoan1 != value))
				{
					this.OnTaiKhoan1Changing(value);
					this.SendPropertyChanging();
					this._TaiKhoan1 = value;
					this.SendPropertyChanged("TaiKhoan1");
					this.OnTaiKhoan1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(100)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="Date")]
		public System.Nullable<System.DateTime> NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVu", DbType="NVarChar(100)")]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this.OnChucVuChanging(value);
					this.SendPropertyChanging();
					this._ChucVu = value;
					this.SendPropertyChanged("ChucVu");
					this.OnChucVuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class sp_inHoaDonBNResult
	{
		
		private string _hoTen;
		
		private string _diaChi;
		
		private string _dienThoai;
		
		private string _idBN;
		
		private System.Nullable<double> _tongTienHD;
		
		private System.Nullable<double> _tongThue;
		
		private System.Nullable<System.DateTime> _ngayLap;
		
		private System.Nullable<int> _soLuong;
		
		private System.Nullable<double> _giaBan;
		
		private System.Nullable<double> _giaBan1;
		
		private string _tenThuoc;
		
		public sp_inHoaDonBNResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoTen", DbType="NVarChar(50)")]
		public string hoTen
		{
			get
			{
				return this._hoTen;
			}
			set
			{
				if ((this._hoTen != value))
				{
					this._hoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(500)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this._diaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dienThoai", DbType="NVarChar(50)")]
		public string dienThoai
		{
			get
			{
				return this._dienThoai;
			}
			set
			{
				if ((this._dienThoai != value))
				{
					this._dienThoai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idBN", DbType="VarChar(50)")]
		public string idBN
		{
			get
			{
				return this._idBN;
			}
			set
			{
				if ((this._idBN != value))
				{
					this._idBN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongTienHD", DbType="Float")]
		public System.Nullable<double> tongTienHD
		{
			get
			{
				return this._tongTienHD;
			}
			set
			{
				if ((this._tongTienHD != value))
				{
					this._tongTienHD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongThue", DbType="Float")]
		public System.Nullable<double> tongThue
		{
			get
			{
				return this._tongThue;
			}
			set
			{
				if ((this._tongThue != value))
				{
					this._tongThue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayLap", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayLap
		{
			get
			{
				return this._ngayLap;
			}
			set
			{
				if ((this._ngayLap != value))
				{
					this._ngayLap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int")]
		public System.Nullable<int> soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this._soLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaBan", DbType="Float")]
		public System.Nullable<double> giaBan
		{
			get
			{
				return this._giaBan;
			}
			set
			{
				if ((this._giaBan != value))
				{
					this._giaBan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaBan1", DbType="Float")]
		public System.Nullable<double> giaBan1
		{
			get
			{
				return this._giaBan1;
			}
			set
			{
				if ((this._giaBan1 != value))
				{
					this._giaBan1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenThuoc", DbType="NVarChar(50)")]
		public string tenThuoc
		{
			get
			{
				return this._tenThuoc;
			}
			set
			{
				if ((this._tenThuoc != value))
				{
					this._tenThuoc = value;
				}
			}
		}
	}
	
	public partial class sp_inHoaDonNhapResult
	{
		
		private string _maHDN;
		
		private System.Nullable<int> _soLuong;
		
		private System.Nullable<double> _giaNhap;
		
		private string _idThuoc;
		
		private string _tenNPP;
		
		private string _tenThuoc;
		
		public sp_inHoaDonNhapResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHDN", DbType="VarChar(50)")]
		public string maHDN
		{
			get
			{
				return this._maHDN;
			}
			set
			{
				if ((this._maHDN != value))
				{
					this._maHDN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int")]
		public System.Nullable<int> soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this._soLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaNhap", DbType="Float")]
		public System.Nullable<double> giaNhap
		{
			get
			{
				return this._giaNhap;
			}
			set
			{
				if ((this._giaNhap != value))
				{
					this._giaNhap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idThuoc", DbType="VarChar(50)")]
		public string idThuoc
		{
			get
			{
				return this._idThuoc;
			}
			set
			{
				if ((this._idThuoc != value))
				{
					this._idThuoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNPP", DbType="NVarChar(100)")]
		public string tenNPP
		{
			get
			{
				return this._tenNPP;
			}
			set
			{
				if ((this._tenNPP != value))
				{
					this._tenNPP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenThuoc", DbType="NVarChar(50)")]
		public string tenThuoc
		{
			get
			{
				return this._tenThuoc;
			}
			set
			{
				if ((this._tenThuoc != value))
				{
					this._tenThuoc = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
