//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLBTEntities : DbContext
    {
        public QLBTEntities()
            : base("name=QLBTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<sp_inHoaDonBN_Result> sp_inHoaDonBN(string idBN)
        {
            var idBNParameter = idBN != null ?
                new ObjectParameter("idBN", idBN) :
                new ObjectParameter("idBN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_inHoaDonBN_Result>("sp_inHoaDonBN", idBNParameter);
        }
    
        public virtual ObjectResult<sp_inHoaDonNhap_Result> sp_inHoaDonNhap(string maHDN)
        {
            var maHDNParameter = maHDN != null ?
                new ObjectParameter("maHDN", maHDN) :
                new ObjectParameter("maHDN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_inHoaDonNhap_Result>("sp_inHoaDonNhap", maHDNParameter);
        }
    }
}
